// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class ABinding  extends Binding {
  public final String stellaident_;
  public final Expr expr_;
  public int line_num, col_num, offset;
  public ABinding(String p1, Expr p2) { stellaident_ = p1; expr_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof ABinding) {
      ABinding x = (ABinding)o;
      return this.stellaident_.equals(x.stellaident_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stellaident_.hashCode())+this.expr_.hashCode();
  }


}
