// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class ALabelledPattern  extends LabelledPattern {
  public final String stellaident_;
  public final Pattern pattern_;
  public int line_num, col_num, offset;
  public ALabelledPattern(String p1, Pattern p2) { stellaident_ = p1; pattern_ = p2; }

  public <R,A> R accept(org.syntax.stella.Absyn.LabelledPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.stella.Absyn.ALabelledPattern) {
      org.syntax.stella.Absyn.ALabelledPattern x = (org.syntax.stella.Absyn.ALabelledPattern)o;
      return this.stellaident_.equals(x.stellaident_) && this.pattern_.equals(x.pattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stellaident_.hashCode())+this.pattern_.hashCode();
  }


}
