// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class AnExtension  extends Extension {
  public final ListExtensionName listextensionname_;
  public int line_num, col_num, offset;
  public AnExtension(ListExtensionName p1) { listextensionname_ = p1; }

  public <R,A> R accept(org.syntax.stella.Absyn.Extension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.stella.Absyn.AnExtension) {
      org.syntax.stella.Absyn.AnExtension x = (org.syntax.stella.Absyn.AnExtension)o;
      return this.listextensionname_.equals(x.listextensionname_);
    }
    return false;
  }

  public int hashCode() {
    return this.listextensionname_.hashCode();
  }


}
