// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class AProgram  extends Program {
  public final LanguageDecl languagedecl_;
  public final ListExtension listextension_;
  public final ListDecl listdecl_;
  public int line_num, col_num, offset;
  public AProgram(LanguageDecl p1, ListExtension p2, ListDecl p3) { languagedecl_ = p1; listextension_ = p2; listdecl_ = p3; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof AProgram) {
      AProgram x = (AProgram)o;
      return this.languagedecl_.equals(x.languagedecl_) && this.listextension_.equals(x.listextension_) && this.listdecl_.equals(x.listdecl_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.languagedecl_.hashCode())+this.listextension_.hashCode())+this.listdecl_.hashCode();
  }


}
