// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class AVariantFieldType  extends VariantFieldType {
  public final String stellaident_;
  public final OptionalTyping optionaltyping_;
  public int line_num, col_num, offset;
  public AVariantFieldType(String p1, OptionalTyping p2) { stellaident_ = p1; optionaltyping_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof AVariantFieldType) {
      AVariantFieldType x = (AVariantFieldType)o;
      return this.stellaident_.equals(x.stellaident_) && this.optionaltyping_.equals(x.optionaltyping_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stellaident_.hashCode())+this.optionaltyping_.hashCode();
  }


}
