// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class DotRecord  extends Expr {
  public final Expr expr_;
  public final String stellaident_;
  public int line_num, col_num, offset;
  public DotRecord(Expr p1, String p2) { expr_ = p1; stellaident_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof DotRecord) {
      DotRecord x = (DotRecord)o;
      return this.expr_.equals(x.expr_) && this.stellaident_.equals(x.stellaident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.stellaident_.hashCode();
  }


}
