// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class Let  extends Expr {
  public final String stellaident_;
  public final Expr expr_1, expr_2;
  public int line_num, col_num, offset;
  public Let(String p1, Expr p2, Expr p3) { stellaident_ = p1; expr_1 = p2; expr_2 = p3; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Let) {
      Let x = (Let)o;
      return this.stellaident_.equals(x.stellaident_) && this.expr_1.equals(x.expr_1) && this.expr_2.equals(x.expr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.stellaident_.hashCode())+this.expr_1.hashCode())+this.expr_2.hashCode();
  }


}
