// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class PatternCons  extends Pattern {
  public final Pattern pattern_1, pattern_2;
  public int line_num, col_num, offset;
  public PatternCons(Pattern p1, Pattern p2) { pattern_1 = p1; pattern_2 = p2; }

  public <R,A> R accept(org.syntax.stella.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.stella.Absyn.PatternCons) {
      org.syntax.stella.Absyn.PatternCons x = (org.syntax.stella.Absyn.PatternCons)o;
      return this.pattern_1.equals(x.pattern_1) && this.pattern_2.equals(x.pattern_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pattern_1.hashCode())+this.pattern_2.hashCode();
  }


}
