// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class PatternRecord  extends Pattern {
  public final ListLabelledPattern listlabelledpattern_;
  public int line_num, col_num, offset;
  public PatternRecord(ListLabelledPattern p1) { listlabelledpattern_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof PatternRecord) {
      PatternRecord x = (PatternRecord)o;
      return this.listlabelledpattern_.equals(x.listlabelledpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.listlabelledpattern_.hashCode();
  }


}
