// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class PatternList  extends Pattern {
  public final ListPattern listpattern_;
  public int line_num, col_num, offset;
  public PatternList(ListPattern p1) { listpattern_ = p1; }

  public <R,A> R accept(org.syntax.stella.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.stella.Absyn.PatternList) {
      org.syntax.stella.Absyn.PatternList x = (org.syntax.stella.Absyn.PatternList)o;
      return this.listpattern_.equals(x.listpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.listpattern_.hashCode();
  }


}
