// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class SomePatternData  extends PatternData {
  public final Pattern pattern_;
  public int line_num, col_num, offset;
  public SomePatternData(Pattern p1) { pattern_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof SomePatternData) {
      SomePatternData x = (SomePatternData)o;
      return this.pattern_.equals(x.pattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.pattern_.hashCode();
  }


}
