// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class TypeSum  extends Type {
  public final Type type_1, type_2;
  public int line_num, col_num, offset;
  public TypeSum(Type p1, Type p2) { type_1 = p1; type_2 = p2; }

  public <R,A> R accept(org.syntax.stella.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.stella.Absyn.TypeSum) {
      org.syntax.stella.Absyn.TypeSum x = (org.syntax.stella.Absyn.TypeSum)o;
      return this.type_1.equals(x.type_1) && this.type_2.equals(x.type_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_1.hashCode())+this.type_2.hashCode();
  }


}
