// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class TypeApplication  extends Expr {
  public final Expr expr_;
  public final ListType listtype_;
  public int line_num, col_num, offset;
  public TypeApplication(Expr p1, ListType p2) { expr_ = p1; listtype_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof TypeApplication) {
      TypeApplication x = (TypeApplication)o;
      return this.expr_.equals(x.expr_) && this.listtype_.equals(x.listtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.listtype_.hashCode();
  }


}
