// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class TypeAbstraction  extends Expr {
  public final ListStellaIdent liststellaident_;
  public final Expr expr_;
  public int line_num, col_num, offset;
  public TypeAbstraction(ListStellaIdent p1, Expr p2) { liststellaident_ = p1; expr_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof TypeAbstraction) {
      TypeAbstraction x = (TypeAbstraction)o;
      return this.liststellaident_.equals(x.liststellaident_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.liststellaident_.hashCode())+this.expr_.hashCode();
  }


}
