// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class TypeForAll  extends Type {
  public final ListStellaIdent liststellaident_;
  public final Type type_;
  public int line_num, col_num, offset;
  public TypeForAll(ListStellaIdent p1, Type p2) { liststellaident_ = p1; type_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof TypeForAll) {
      TypeForAll x = (TypeForAll)o;
      return this.liststellaident_.equals(x.liststellaident_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.liststellaident_.hashCode())+this.type_.hashCode();
  }


}
