// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class TypeTuple  extends Type {
  public final ListType listtype_;
  public int line_num, col_num, offset;
  public TypeTuple(ListType p1) { listtype_ = p1; }

  public <R,A> R accept(org.syntax.stella.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.stella.Absyn.TypeTuple) {
      org.syntax.stella.Absyn.TypeTuple x = (org.syntax.stella.Absyn.TypeTuple)o;
      return this.listtype_.equals(x.listtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtype_.hashCode();
  }


}
