// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class Variant  extends Expr {
  public final String stellaident_;
  public final ExprData exprdata_;
  public int line_num, col_num, offset;
  public Variant(String p1, ExprData p2) { stellaident_ = p1; exprdata_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Variant) {
      Variant x = (Variant)o;
      return this.stellaident_.equals(x.stellaident_) && this.exprdata_.equals(x.exprdata_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stellaident_.hashCode())+this.exprdata_.hashCode();
  }


}
